version: "3.4"

networks:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    user: 1000:1000

    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - grafana

    ports:
      - "8086:8086"

    environment:
      - INFLUXDB_DB=k6

    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    depends_on:
      - influxdb

    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: grafana/k6
    container_name: k6

    network_mode: host

    environment:
      - K6_OUT=influxdb=http://localhost:8086/k6
    volumes:
      - ./scripts:/scripts

    entrypoint: k6 run /scripts/eworks.js
